
<br><br><br>
<h2><font size=6>Práctica 0</font></h2>



<h1><font size=7>Introducción a Pandas y Numpy </font></h1>

<br>
<div style="text-align: right">
<font size=4>Pablo Torrijos Arenas (Pablo.Torrijos@uclm.es)</font><br>
<font size=4>José Miguel Puerta Callejón (Jose.Puerta@uclm.es)</font><br>
</div>

## 1. Pandas 

Pandas es una de las librerías más utilizadas en el análisis y visualización de datos. Sus funciones están pensadas para hacer filtros y obtener estadísticos de grandes bases de datos de forma óptima.  Esta librería se basa en los DataFrames de R. Es una herramienta muy potente con una curva de aprendizaje compleja. En esta práctica veremos algunas funciones básicas para su uso y que serán más que suficiente para la asginatura.

In [149]:
# Import system libraries
import random

# Import third party libraries
import pandas as pd
import numpy as np

In [150]:
# Siempre que tratamos con algun valor aleatorio, lo primero es fijar la semilla

seed = 42
random.seed(seed)
np.random.seed(seed)

### Carga de datasets

La mayoría de las veces, el primer paso en Pandas será cargar un dataset. Hay múltiples maneras de hacerlo pero a lo largo de este curso vamos a trabajar principalmente con archivos csv. Para cargarlos, podemos hacer lo siguiente:

In [151]:
path = 'notas.csv' # Definimos la ruta donde estará nuestro conjunto de datos
#Anotación del pepas: Si está en el mismo directorio de carpeta, con colo nombre basta+
#Los velociraptors molan mucho, pero no se pueden tener como mascotas, aunque molen mucho.

df = pd.read_csv(path, index_col=0) # Si el dataset tiene indice lo marcamos, de otra manera es automatico
#index_col es el num columna usamos índice
df

Nombre  Teoria  Practica
0         Alumno 1     2.7       1.6
1         Alumno 2     2.6       5.0
2         Alumno 3     4.1       7.0
3         Alumno 4     1.8       7.8
4         Alumno 5     3.2       7.5
...            ...     ...       ...
9995   Alumno 9996     5.1       6.6
9996   Alumno 9997     8.2       2.4
9997   Alumno 9998     9.3       7.9
9998   Alumno 9999     4.1       1.7
9999  Alumno 10000     4.1       1.5

[10000 rows x 3 columns]

### Estudio del conjunto de datos

Normalmente no conocemos el contenido de nuestro dataset, para ello podemos ver su contenido con distintas funciones:

In [152]:
df.head(5) # Cogemos los primeros 5 elementos del dataset

Nombre  Teoria  Practica
0  Alumno 1     2.7       1.6
1  Alumno 2     2.6       5.0
2  Alumno 3     4.1       7.0
3  Alumno 4     1.8       7.8
4  Alumno 5     3.2       7.5

In [153]:
df.sample(10, random_state=seed) # Muestreamos 10 elementos al azar del dataset
#random_state es la semilla para que siempre nos de los mismos resultados, si no se pone, cada vez que se ejecute el código, dará resultados diferentes

Nombre  Teoria  Practica
6252  Alumno 6253     8.0       2.7
4684  Alumno 4685     4.5       8.2
1731  Alumno 1732     3.1       6.7
4742  Alumno 4743     9.4       7.4
4521  Alumno 4522     2.6       8.2
6340  Alumno 6341     2.8       7.5
576    Alumno 577     0.5       8.1
5202  Alumno 5203     0.2       3.5
6363  Alumno 6364     1.4       1.3
439    Alumno 440     1.7       4.8

In [154]:
df.info() # Mostramos las variables del dataset así como su tipo, valores perdidos, etc

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Nombre    10000 non-null  object 
 1   Teoria    10000 non-null  float64
 2   Practica  10000 non-null  float64
dtypes: float64(2), object(1)
memory usage: 312.5+ KB


In [155]:
df.describe() # Finalmente observamos algunas estadísticas como la media, el número de valores totale,s los cuartiles, etc.

Teoria      Practica
count  10000.00000  10000.000000
mean       4.95798      4.972600
std        2.87663      2.886254
min        0.00000      0.000000
25%        2.50000      2.500000
50%        5.00000      5.000000
75%        7.40000      7.500000
max        9.90000      9.900000

### Slicing

Hay veces que queremos particionar o filtrar el dataset. Para ello, Pandas proporciona distintas funciones para hacerlo de manera eficiente

In [156]:
# Vamos a coger un muestreo aleatorio como hemos visto anteriormente para trabajar en esta seccion
sample_df = df.sample(10, random_state=seed)
sample_df

Nombre  Teoria  Practica
6252  Alumno 6253     8.0       2.7
4684  Alumno 4685     4.5       8.2
1731  Alumno 1732     3.1       6.7
4742  Alumno 4743     9.4       7.4
4521  Alumno 4522     2.6       8.2
6340  Alumno 6341     2.8       7.5
576    Alumno 577     0.5       8.1
5202  Alumno 5203     0.2       3.5
6363  Alumno 6364     1.4       1.3
439    Alumno 440     1.7       4.8

#### `loc`

La función `loc` escoge los elementos de acuerdo con su índice. Esto quiere decir que, si es un muestreo aleatorio del Dataframe, necesitamos conocer los valores de los índices. 

In [157]:
# Si queremos coger el valor de la primera fila del dataset conocemos que su indice es 6252
sample_df.loc[6252]

Nombre      Alumno 6253
Teoria              8.0
Practica            2.7
Name: 6252, dtype: object

#### `iloc`

Por otro lado, la función `iloc` escoge los elementos de acuerdo con su indice relativo. Esto quiere decir que para escoger un elemento no necesitamos saber su indice sino su posición

In [158]:
# Si queremos coger el valor de la primera fila del dataset conocemos que su posicion es 0
sample_df.iloc[1]


Nombre      Alumno 4685
Teoria              4.5
Practica            8.2
Name: 4684, dtype: object

Estos métodos funcionan igual que el _slicing_ en listas en Python, es decir, permite coger rangos, definir saltos, etc...

In [159]:
# Para coger las 5 primeras filas del DataFrame
sample_df.iloc[:5]

Nombre  Teoria  Practica
6252  Alumno 6253     8.0       2.7
4684  Alumno 4685     4.5       8.2
1731  Alumno 1732     3.1       6.7
4742  Alumno 4743     9.4       7.4
4521  Alumno 4522     2.6       8.2

Finalmente, un DataFrame se considera como un array bidimensional, de tal manera que se puede utilizar la misma notación para escoger columnas

In [160]:
# Queremos coger todas las filas de la columna de teoria
sample_df.loc[:, 'Teoria']

6252    8.0
4684    4.5
1731    3.1
4742    9.4
4521    2.6
6340    2.8
576     0.5
5202    0.2
6363    1.4
439     1.7
Name: Teoria, dtype: float64

In [161]:
sample_df['Teoria']

6252    8.0
4684    4.5
1731    3.1
4742    9.4
4521    2.6
6340    2.8
576     0.5
5202    0.2
6363    1.4
439     1.7
Name: Teoria, dtype: float64

In [162]:
# O sabiendo que la columna de teoria es la segunda (indice 1)
sample_df.iloc[:,1]

6252    8.0
4684    4.5
1731    3.1
4742    9.4
4521    2.6
6340    2.8
576     0.5
5202    0.2
6363    1.4
439     1.7
Name: Teoria, dtype: float64

In [234]:
# Ejercicio 1: Crear un muestreo aleatorio de 30 elementos del dataframe original 
# y coger los elementos del 15 al 23 de las columnas práctica y teoría
# TODO
# Vamos a coger un muestreo aleatorio como hemos visto anteriormente para trabajar en esta seccion


muestroAleaTreinta = df.sample(30, random_state=seed) #df es dataframe original
# muestroAleaTreinta

muestroAleaTreinta.iloc[15:24:, 1:3] #iloc es por posición sacada en random, el rango es hasta 24 porque no incluye el último elemento

                                    #1:3 pq teoria es 1 y practica 2


Teoria  Practica
6033     7.1       3.3
582      2.6       3.8
9930     3.4       3.9
7051     0.3       4.7
8158     2.4       6.5
9896     1.7       0.0
2249     1.2       1.3
4640     3.5       5.5
9485     0.8       5.7

### Condiciones

Además de indexar el Dataframe, una de las funciones más potentes de Pandas es que permite filtrar los Dataframes por condiciones utilizando la función `loc`

In [164]:
# Si queremos sacar todos los alumnos con teoria aprobada
df.loc[(df['Teoria'] > 5)]

Nombre  Teoria  Practica
5        Alumno 6     5.9       4.7
8        Alumno 9     6.8       7.0
10      Alumno 11     7.0       3.4
13      Alumno 14     7.6       4.2
16      Alumno 17     7.8       8.3
...           ...     ...       ...
9992  Alumno 9993     6.9       4.4
9993  Alumno 9994     6.3       8.9
9995  Alumno 9996     5.1       6.6
9996  Alumno 9997     8.2       2.4
9997  Alumno 9998     9.3       7.9

[4936 rows x 3 columns]

Para añadir múltiples condiciones, tienen que ir englobadas en paréntesis e ir seguidas de un `&` o un `|`, ya que son operadores lógicos, no booleanos

In [165]:
# Si queremos sacar todos los alumnos con teoria y practica aprobadas
df.loc[(df['Teoria'] > 5) & (df['Practica'] > 5)]

Nombre  Teoria  Practica
8        Alumno 9     6.8       7.0
16      Alumno 17     7.8       8.3
23      Alumno 24     6.2       6.8
28      Alumno 29     7.4       5.9
33      Alumno 34     7.3       8.2
...           ...     ...       ...
9981  Alumno 9982     8.7       5.9
9989  Alumno 9990     8.4       5.2
9993  Alumno 9994     6.3       8.9
9995  Alumno 9996     5.1       6.6
9997  Alumno 9998     9.3       7.9

[2459 rows x 3 columns]

### Creación de características

Otra función muy potente de Pandas es que nos permite la creación de características a partir de las columnas que ya tenemos sin tener que iterar.

In [166]:
# Si queremos crear la nota final a partir de 0.6*Teoria + 0.4*Practica
df['Final'] = df['Teoria']*0.6 + df['Practica']*0.4
df

Nombre  Teoria  Practica  Final
0         Alumno 1     2.7       1.6   2.26
1         Alumno 2     2.6       5.0   3.56
2         Alumno 3     4.1       7.0   5.26
3         Alumno 4     1.8       7.8   4.20
4         Alumno 5     3.2       7.5   4.92
...            ...     ...       ...    ...
9995   Alumno 9996     5.1       6.6   5.70
9996   Alumno 9997     8.2       2.4   5.88
9997   Alumno 9998     9.3       7.9   8.74
9998   Alumno 9999     4.1       1.7   3.14
9999  Alumno 10000     4.1       1.5   3.06

[10000 rows x 4 columns]

No solo lo podemos hacer en una linea, podemos crear funciones auxiliares y luego aplicarlas para crear características

In [167]:
def nota_final(teoria, practica):
    return teoria*0.6 + practica*0.4

df['Final2'] = nota_final(df['Teoria'], df['Practica'])
df

Nombre  Teoria  Practica  Final  Final2
0         Alumno 1     2.7       1.6   2.26    2.26
1         Alumno 2     2.6       5.0   3.56    3.56
2         Alumno 3     4.1       7.0   5.26    5.26
3         Alumno 4     1.8       7.8   4.20    4.20
4         Alumno 5     3.2       7.5   4.92    4.92
...            ...     ...       ...    ...     ...
9995   Alumno 9996     5.1       6.6   5.70    5.70
9996   Alumno 9997     8.2       2.4   5.88    5.88
9997   Alumno 9998     9.3       7.9   8.74    8.74
9998   Alumno 9999     4.1       1.7   3.14    3.14
9999  Alumno 10000     4.1       1.5   3.06    3.06

[10000 rows x 5 columns]

In [ ]:
# Ejercicio 2: Crear una nueva columna 'Ejercicio' que sea:
# - 'Suspenso' si ha suspendido teoria y practica
# - 'Guarda Practicas' si ha aprobado practicas y ha suspendido teoria con un 4 o mas
# - 'Guarda Teoria' si ha aprobado teoria y ha suspendido practicas con un 4 o mas
# - 'Aprobado' si ha aprobado ambas y tiene media menos de 7
# - 'Notable' si ha aprobado ambas y tiene media entre 7 y 9
# - 'Sobresaliente' si ha aprobado ambas y tiene media entre 9 y 10

# TODO: Programar aqui

# df.loc[(df['Teoria'] > 5) & (df['Practica'] > 5)]
# df['Final2'] = nota_final(df['Teoria'], df['Practica'])



df['Ejercicio'] = '' # Por defecto, todos los alumnos son suspensos



if (df.loc[(df['Teoria'] > 5) ]):
    df['Ejercicio'] = 'Aprobado'



ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

## 2. Numpy

Pandas es una gran librería para visualización, pero no es demasiado eficiente cuando hay que realizar operaciones complejas con conjunto de datos, por ejemplo entrenar un clasificador. Para ello, utilizaremos Numpy.

Esta librería permite operaciones eficientes de matrices, y está programada en C y FORTRAN, siendo la mejor opción para programar algunas funciones a lo largo de la asignatura.  

### Creación de Matrices

Al contrario que las listas de Python, los arrays de Numpy son estáticos. Esto quiere decir que no podemos añadir nuevos elementos a posteriori, sino que tenemos que crear una matriz del tamaño de nuestros datos y luego modificar los distintos índices. Para ello tenemos múltiples funciones:

In [169]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [170]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Se puede crear una lista en Python y transformarla en un array de Numpy:

In [171]:
lista = [1,2,3,4,5]
np.array(lista)

array([1, 2, 3, 4, 5])

O se pueden crear arrays con rangos:

In [172]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### Operaciones 

Las matrices se pueden operar entre sí:

In [173]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a + b

array([ 6,  8, 10, 12])

In [174]:
a * b

array([ 5, 12, 21, 32])

### Funciones universales

Numpy además proporciona ciertas funciones generales:

In [175]:
np.max(a+b)

np.int64(12)

In [176]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

### Slicing

Al igual que Pandas o Python, también se puede hacer slicing con los arrays de Numpy

In [177]:
a[2:4]

array([3, 4])

In [178]:
# Ejercicio 3: Crear una matriz de 7*7 donde la columna central sea la serie de fibonacci, y cada columna a la derecha sea sumar uno y a la izquierda sea restar uno. 
# Un ejemplo de una matriz 5*5 asi seria:
# -1 0 1 2 3
# -1 0 1 2 3
#  0 1 2 3 4
#  1 2 3 4 5
#  3 4 5 6 7

# TODO: Programar aqui

### Indexado y condiciones

Equivalente a Pandas, se pueden definir condiciones para filtrar un array en Numpy. Hacer una "pregunta" a un array devolverá un vector booleano sobre la satisfacción de la pregunta. Ese mismo vector se puede utilizar para escoger solo ciertos elementos del array.

In [179]:
a = np.array([1,2,3,4,5])
cond = a > 3
cond

array([False, False, False,  True,  True])

In [180]:
a[cond]

array([4, 5])

Yendo más allá, se puede usar la condición de un array para escoger los elementos de otro con las mismas dimensiones

In [181]:
teoria = np.array([0,3,5,7,9])
practica = np.array([3,0,5,1,9])

practica[teoria >= 5] # Que notas de practica tiene la gente que ha aprobado la teoria?

array([5, 1, 9])

Por otra parte se puede usar un array como los indices que seleccionar de otro array

In [182]:
idx = [2,1,4]
teoria[idx]

array([5, 3, 9])

In [183]:
# Ejercicio 4: Usando la matriz del Ejercicio 3, obtener la lista de
# elementos que sean mayores o igual que 2 y menores que 10

# TODO: Programar aqui

### Stacking and reshaping

Los arrays de Numpy pueden tener una o múltiples dimensiones, y a veces queremos que tengan una forma concreta. 

A veces tenemos multiples array que queremos combinar en uno solo:

In [184]:
# Podemos ver que el array teoria tiene una sola dimension con 5 elementos

teoria.shape

(5,)

In [185]:
teoria

array([0, 3, 5, 7, 9])

In [186]:
# Si queremos hacer que en vez de 5 columnas y 1 fila, sea 1 columna y 5 filas, podemos cambiarle la forma al array

teoria.reshape(-1, 1)

array([[0],
       [3],
       [5],
       [7],
       [9]])

In [187]:
teoria.reshape(-1, 1).shape

(5, 1)

In [188]:
# Si queremos concatenar los array de teoria y practica en uno solo
# podemos unirlos 'horizontalmente'

np.hstack([teoria, practica])

array([0, 3, 5, 7, 9, 3, 0, 5, 1, 9])

In [189]:
# Si en lugar de concatenarlos queremos crear una matriz de 2 dimensiones
# podemos unirlos 'verticalmente'

np.vstack([teoria, practica])

array([[0, 3, 5, 7, 9],
       [3, 0, 5, 1, 9]])

In [190]:
# Ejercicio 5: Usando la matriz del Ejercicio 4, reordenarla 
# para que todos sus elementos estén en una única columna

# TODO: Programar aquí

### Preguntas

Podemos obtener condiciones que cumple un array, con las preguntas `any` y `all`

In [191]:
teoria > 5

array([False, False, False,  True,  True])

In [192]:
# Si queremos saber si alguien ha aprobado teoria

if np.any(teoria > 5):
    print('Alguien ha aprobado teoria')
else:
    print('Nadie ha aprobado teoria')

Alguien ha aprobado teoria


In [193]:
# Si queremos saber si todo el mundo ha aprobado practica

if np.all(practica > 5):
    print('Todo el mundo ha aprobado practica')
else:
    print('Alguien ha suspendido practica')

Alguien ha suspendido practica


### Orden y otras funciones

Al igual que una lista normal de Python, los arrays de Numpy se pueden reordenar

In [194]:
np.sort(practica)

array([0, 1, 3, 5, 9])

Pero una de los tipos de funciones más interesantes son aquellas que empiezan por `arg`. En lugar de devolvernos el resultado de la función, nos devuelve los índices del resultado de la función. Así, `argsort` nos devolverá los índices que ordenan una matriz, en lugar de la matriz ordenada.

In [195]:
idx = np.argsort(practica)
print(practica[idx])

# Pero y si queremos ordenar el array de teoria en funcion de las mejores notas de práctica?
teoria[idx]

[0 1 3 5 9]


array([3, 7, 0, 5, 9])

In [196]:
# Orden inverso:
teoria[idx[::-1]]

array([9, 5, 0, 7, 3])

In [197]:
# Qué nota de teoría tiene la persona con mejor nota de práctica?
idx = np.argmax(practica)
teoria[idx]

np.int64(9)

### Pandas y Numpy

Estas dos librerías que hemos visto en la práctica son similares, y tienen interfaces para pasar de una a otra. 

In [198]:
# Para convertir un dataframe a numpy

df.to_numpy()

array([['Alumno 1', 2.7, 1.6, 2.2600000000000002, 2.2600000000000002],
       ['Alumno 2', 2.6, 5.0, 3.56, 3.56],
       ['Alumno 3', 4.1, 7.0, 5.26, 5.26],
       ...,
       ['Alumno 9998', 9.3, 7.9, 8.74, 8.74],
       ['Alumno 9999', 4.1, 1.7, 3.1399999999999997, 3.1399999999999997],
       ['Alumno 10000', 4.1, 1.5, 3.0599999999999996, 3.0599999999999996]],
      shape=(10000, 5), dtype=object)

In [199]:
# Para convertir un array de numpy a dataframe
pd.DataFrame(np.vstack([teoria, practica]).T, columns=['Teoria', 'Practica'])

Teoria  Practica
0       0         3
1       3         0
2       5         5
3       7         1
4       9         9

### Eficiencia

Una de las mayores razones por la que usar una librería u otra en cada momento es por eficiencia. Numpy es mucho más eficiente que Pandas a la hora de iterar sus datos, algo que se realizará en múltiples ocasiones en esta asignatura. 

In [200]:
from time import perf_counter
df_np = df.to_numpy()

In [201]:
# Ver que nota de teoria es mayor que practicas -> Pandas iterrows()
counter = 0

perf = perf_counter()
for i,row in df.iterrows():
    if row['Teoria'] > row['Practica']:
        counter += 1
perfPd = perf_counter() - perf

print(counter, "notas. ", "Pandas iterrows():", perfPd.__round__(5), "segundos")

4895 notas.  Pandas iterrows(): 0.24487 segundos


In [202]:
# Ver que nota de teoria es mayor que practicas -> Numpy bucle for
counter = 0

perf = perf_counter()
for _, t, p, _,  _ in df_np:
    if t > p:
        counter += 1
perfNp = perf_counter() - perf

print(str(counter) + " notas.  Numpy: " + str(perfNp.__round__(5)) + " segundos")

4895 notas.  Numpy: 0.00838 segundos


Sin embargo, más importante aún que elegir usar Pandas o Numpy es el uso de operaciones vectorizadas siempre que sea posible. Python es un lenguaje MUY lento, principalmente al no ser compilado, por lo que cada bucle `for` que nos podamos ahorrar reemplazándolo por alguna operación vectorizada programada internamente en `C` hará que nuestro código vaya mucho más rápido.

In [203]:
# Ver que nota de teoria es mayor que practicas -> Pandas vectorizado
counter = 0

perf = perf_counter()
counter = df[df['Teoria'] > df['Practica']].shape[0]
perfPdV = perf_counter() - perf

print(counter, "notas. ", "Pandas:", perfPdV.__round__(5), "segundos")

4895 notas.  Pandas: 0.00146 segundos


In [204]:
# Ver que nota de teoria es mayor que practicas -> Numpy vectorizado
counter = 0

perf = perf_counter()
counter = np.sum(df_np[:,1] > df_np[:,2])
perfNpV = perf_counter() - perf

print(str(counter) + " notas.  Numpy vectorizado: " + str(perfNpV.__round__(5)) + " segundos")

4895 notas.  Numpy vectorizado: 0.0003 segundos


In [205]:
# Algunas métricas
print("Ganancia de velocidad de Numpy sobre Pandas (bucle for):", (perfPd/perfNp).__round__(2))
print("Ganancia de velocidad de Numpy sobre Pandas (vectorizado):", (perfPdV/perfNpV).__round__(2))

print("\nGanancia de velocidad de Pandas al vectorizar:", (perfPd/perfPdV).__round__(2))
print("Ganancia de velocidad de Numpy al vectorizar:", (perfNp/perfNpV).__round__(2))

Ganancia de velocidad de Numpy sobre Pandas (bucle for): 29.21
Ganancia de velocidad de Numpy sobre Pandas (vectorizado): 4.82

Ganancia de velocidad de Pandas al vectorizar: 167.3
Ganancia de velocidad de Numpy al vectorizar: 27.6
